### ISSUE TITLE
Vivint is discontinuing web access "by the end of this year" (2020)

### ISSUE THREAD

**Issue by doctorkb** [ovirs/pyvivint#6]
I just logged in to my control panel and noticed that Vivint is discontinuing the web access and only their mobile apps will be able to control the system.

Not sure if this is something that can be worked around or not.

**Comment by ovirs** [comment]
Didn't really had time to work on this in a while, but last I checked both the web and the mobile app were using the same API, so it shouldn't matter.

I will finally have more time starting next week and planning to resume work on this and also finalize the home-assistant integration too

**Comment by doctorkb** [comment]
Awesome.  In case you're looking for alternatives, it looks like the HomeBridge integration connects slightly differently...

https://github.com/balansse/homebridge-vivint/blob/master/lib/vivint_api.js

I'd offer to help, but my python skills are about, well, "does indent really matter?" 😄 

I've been using your library for a while and it looks like Vivint is either having an issue with redirects (web interface sucked today) or is in the process of shutting things down.  Apparently, this change is to assist in implementing two-factor authentication, so my gut says the latter, as it seemed to have a lot of trouble ending up on the "app" screen, often passing through it to end on the "account" screen.

**Comment by ovirs** [comment]
thanks! I'll take a look. Yes - just noticed I've been getting lots of errors from their API today.

**Comment by ovirs** [comment]
this should be now addressed by the changes submitted by @natekspencer and released in version 2021.1.1
